source 'https://github.com/CocoaPods/Specs.git'

target 'SSSKit', :exclusive => true do
  pod "SSSKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SSSKit", :path => "../"

  
end
